profile: build

shared:
  ingress_domain: tanzu-tmm-demo.com

ceip_policy_disclosed: true # Installation fails if this is set to 'false'

buildservice:
  kp_default_repository: harbor.ryanbaker.io/tap-tbs/tbs
  kp_default_repository_password: <redacted>
  kp_default_repository_username: <redacted>

grype:
  targetImagePullSecret: registry-credentials
  metadataStore:
    url: https://metadata-store.tanzu-tmm-demo.com
    # copied from view cluster
    caSecret:
        name: store-ca-cert
        importFromNamespace: metadata-store-secrets
    authSecret:
        name: store-auth-token
        importFromNamespace: metadata-store-secrets

scanning:
  metadataStore:
    url: "" # Disable embedded integration since it's deprecated

supply_chain: testing_scanning

ootb_supply_chain_testing_scanning:
  scanning:
    image:
      template: snyk-private-image-scan-template
      policy: scan-policy
  registry:
    server: harbor.ryanbaker.io
    repository: tap-apps
  gitops:
    server_address: "https://github.com/"
    repository_owner: "tmm-tanzu"
    repository_name: "tap-gitops"
    branch: stage
    user_name: tanzu-demo
    user_email: tanzu-demo@vmware.com
    commit_strategy: pull_request
    pull_request:
      server_kind: github
      commit_branch: ""
      pull_request_title: "Ready for review"
      pull_request_body: "Generated by TAP supply chain"

contour:
  envoy:
    service:
      type: LoadBalancer